### ISSUE TITLE
JAR

### ISSUE THREAD

**Issue by bobboteck** [officinerobotiche/orblibjar#7]
@rbonghi you think is possible generate JAR file of library, and put it in the repository?

**Comment by rbonghi** [comment]
Fine!
You should be download on my  temporary dropbox link: **REMOVED**

**Comment by bobboteck** [comment]
But put it (final version) in a specific folder of repository?

**Comment by rbonghi** [comment]
Well
I will put on github using this feature: https://github.com/blog/1547-release-your-software

**Comment by rbonghi** [comment]
Pre-released version of O-RBlibjar :+1: 

https://github.com/officinerobotiche/orblibjar/releases/tag/v0.1
